#+TITLE: Data Science with Pandas
#+AUTHOR: René Steetskamp
#+EMAIL: steets@otech.nl

[[https://pandas.pydata.org/][Home]] | [[http://ehneilsen.net/notebook/pandasExamples/pandas_examples.html][Cookbook]]

Data science is learning from data in order to gain useful predictions and insights and consists of the steps below[fn::https://cs109.github.io]:


1. *Ask* an interesting question:
    1. What is the scientific *goal*?
    2. What would you do if you had all the *data*?
    3. What do you want to *predict* or *estimate*?
2. *GET* the data:
    1. How were the data *sampled*?
    2. Which data are *relevant*?
    3. Are there *privacy* or *copyright* issues?
3. *EXPLORE* the data:
    1. *Plot* the data.
    2. Are there *anomalies*?
    3. Are there *patterns*?
4. *MODEL* the data:
    1. *Build* a model.
    2. *Fit* the model.
    3. *Validate* the model.
5. *Communicate* and *visualize* the results:
    1. What did we *learn*?
    2. Do the results make *sense*?
    3. Can we tell a *story*?


Data science can roughly be split into data engineering and data analysis. Data /engineering/ consists of gathering and preparing data for analysis by [[/posts/scrapy][scraping]], cleaning, correcting, integrating, re-ordering, scaling, converting, etc. In other words, data engineers transform data into formats that data scientists can analyze. For a good introduction to data /analysis/, sign up for the free [[https://eu.udacity.com/course/intro-to-data-analysis--ud170][Udacity course]].

In the Python ecosystem, [[https://pandas.pydata.org][Pandas]] (member of the [[https://pydata.org/downloads.html][PyData]] Python Open Data Science Stack) is /the/ framework for data engineering, although others exist, like [[http://bubbles.databrewery.org/][Bubbles]].
