#+TITLE: Notes
#+AUTHOR: René Steetskamp
#+EMAIL: steets@otech.nl

A collection of notes on several subjects.

* Principles

  When developing I try to apply the following principles:

- I prefer _open technologies_: I use open source software (OSS) whenever I can. And practically the only times that I can't involve working together on Microsoft Office documents.
- _DRY_ (Don't repeat yourself): I try to solve everything only once.
- I don't want to _re-invent the wheel_. That is: if a tool is available, I try to use it. Even if it doesn't fit 100%.
- I try to use tools _as-is_ as much as possible. Also, I try to use standard tools, rather than their more sophisticated alternatives.
- I try to be a _fast-follower_, instead of jumping on every new hype.
- _Design patterns_ are an powerful way to exchange knowledge.

In 1998 the original developer or Tcl/TK, John Ousterhout, [[http://www.tcl.tk/doc/scripting.html][wrote]]:

#+BEGIN_QUOTE
Scripting languages are designed for "gluing" applications; they use typeless approaches to achieve a higher level of programming and more rapid application development than system programming languages. Increases in computer speed and changes in the application mix are making scripting languages more and more important for applications of the future.
#+END_QUOTE

* My preferred tools

- [[file:emacs.org][Emacs]] (or sometimes [[https://code.visualstudio.com/][Code]]) for code editing.
- [[file:python.org][Python]] and [[file:javascript.org][Javascript]] for programming.
- [[https://git-scm.com/doc][Git]] for version management and [[https://github.com/otech-nl][Github]] for sharing my code, issue management, and (Kanban) boards.
- [[file:vagrant.org][Vagrant]] for managing development environments where [[file:python.org][Python's virtual environments]] are not enough.
- [[file:orgmode.org][org-mode]] (and sometimes [[https://daringfireball.net/projects/markdown/syntax][Markdown]]) for plain text editing.

  Finally, some of my favorite web-sites for tech information:

- [[https://scotch.io/][Scotch.io]] provides some really nice tutorials.

  I prefer to work on [[https://www.ubuntu.com/][Ubuntu]], but are sometimes forced to work on Windows. Therefore all my tools preferably work on both.
